### ISSUE TITLE
dhmsw guiserver error

### ISSUE THREAD

**Issue by MrWizard2000** [dhm-org/dhm_suite#2]
When doing the usual:
* Select camera as source
* Select Holograms Only
* Select Open Hologram Display
* Select Run

dhmsw returns with this stack trace:
Watchdog: "guiserver" beat ts=1562185903, exception=YES
Process Guiserver-3:
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/home/ryzen/Desktop/public_git/dhm_suite/dhmsw/dhmsw/guiserver.py", line 282, in run
    raise e
  File "/home/ryzen/Desktop/public_git/dhm_suite/dhmsw/dhmsw/guiserver.py", line 253, in run
    self.process_image(data)
  File "/home/ryzen/Desktop/public_git/dhm_suite/dhmsw/dhmsw/guiserver.py", line 186, in process_image
    a.append(image)
  File "/home/ryzen/Desktop/public_git/dhm_suite/dhmsw/dhmsw/interface.py", line 89, in append
    return self.serialize(data, append=True)
  File "/home/ryzen/Desktop/public_git/dhm_suite/dhmsw/dhmsw/interface.py", line 77, in serialize
    binarystr += self.ndim_struct.pack(data.ndim) + b''.join([struct.pack('H',c) for c in data.shape])
  File "/home/ryzen/Desktop/public_git/dhm_suite/dhmsw/dhmsw/interface.py", line 77, in <listcomp>
    binarystr += self.ndim_struct.pack(data.ndim) + b''.join([struct.pack('H',c) for c in data.shape])
struct.error: ushort format requires 0 <= number <= (0x7fff * 2 + 1)

**Comment by MrWizard2000** [comment]
Maybe due to changes in the header info?

**Comment by sfregoso** [comment]
Yes, this bug is caused by the newly added camserver headers that were not added to the dhmsw.  I just commited changes to interface.py and framesource.py which fixes this error.
