### ISSUE TITLE
Error during reconstruction example: TypeError: cannot pickle 'Struct' object

### ISSUE THREAD

**Issue by wronk** [dhm-org/dhm_suite#25]
## Issue
I'm trying to run the single reconstruction examples [here](https://github.com/dhm-org/dhm_suite/tree/master/dhmsw#examples) and running into an issue with pickle. I've run a `python setup.py install` on `dhmsw` and `shampoo_lite` (see #24). Running `python -m dhmsw.main` ends in the error below.

I did have to use `sudo` to run those installation commands ☝️ It seems like maybe I shouldn't need to do that, so I don't know if there's some sort of deeper permissions issue? At the same time, it doesn't seem like that'd affect pickle's functionality. 

## System
MacOS 10.15.6
Python v3.8.3
Fresh virtual environment

## Full stack trace
```
(dhmx) wronk@MacBook-Pro dhm_suite % python -m dhmsw.main
Import FFT utilities from "pyfftw_utils"
ConfigFile = [/Users/wronk/Builds/dhm_suite/dhmsw/dhmsw/DEFAULT.ini]
centerx:  702.0
centery:  749.0
radius:  170.0
centerx:  702.0
centery:  749.0
radius:  170.0
centerx:  702.0
centery:  749.0
radius:  170.0
centerx:  702.0
centery:  749.0
radius:  170.0
centerx:  702.0
centery:  749.0
radius:  170.0
centerx:  702.0
centery:  749.0
radius:  170.0
Import FFT utilities from "pyfftw_utils"
[RECONSTRUCTOR] Consumer thread started
Traceback (most recent call last):
  File "/Users/wronk/.pyenv/versions/3.8.3/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Users/wronk/.pyenv/versions/3.8.3/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/wronk/Builds/dhm_suite/dhmsw/dhmsw/main.py", line 240, in <module>
    main()
  File "/Users/wronk/Builds/dhm_suite/dhmsw/dhmsw/main.py", line 221, in main
    comp.start()
  File "/Users/wronk/.pyenv/versions/3.8.3/lib/python3.8/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/Users/wronk/.pyenv/versions/3.8.3/lib/python3.8/multiprocessing/context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "/Users/wronk/.pyenv/versions/3.8.3/lib/python3.8/multiprocessing/context.py", line 283, in _Popen
    return Popen(process_obj)
  File "/Users/wronk/.pyenv/versions/3.8.3/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/Users/wronk/.pyenv/versions/3.8.3/lib/python3.8/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/Users/wronk/.pyenv/versions/3.8.3/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 47, in _launch
    reduction.dump(process_obj, fp)
  File "/Users/wronk/.pyenv/versions/3.8.3/lib/python3.8/multiprocessing/reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
TypeError: cannot pickle 'Struct' object
```

**Comment by sfregoso** [comment]
Are you using an Anaconda Python flavor, or a pure python version?

**Comment by wronk** [comment]
@sfregoso, I install python versions via [pyenv](https://github.com/pyenv/pyenv), so I believe it's just pure python?
