### ISSUE TITLE
dhmsw: When enabling amplitude reconstruction, reconstructor dies

### ISSUE THREAD

**Issue by MrWizard2000** [dhm-org/dhm_suite#4]
When selecting:
* Camera
* Amplitude
* Opening displays --
   - Hologram
   - Amplitude
   - Fourier

The reconstructor dies during the selection of Amplitude. Below is output from dhmsw:
```
1562625425.910985: Got command!
Closed client socket
Framesource: Received "Reconstruction_Metadata"
QSize = 1 <class 'dhmsw.interface.GuiPacket'>
Guiserver: Received meta of type:  <class 'dhmsw.metadata_classes.Reconstruction_Metadata'>
Received: [guiserver enable_rawframes=true]
['enable_rawframes=true']
enable_rawframes=true
2
cmd_str:  guiserver enable_rawframes=true
cmd_dict:  {'guiserver': {'enable_rawframes': 'true'}}
Key: [guiserver]
{'enable_rawframes': 'true'}
Param_out[enable_rawframes]= True <class 'bool'>
Returned command: {'guiserver': {'enable_rawframes': True}}
1562625426.974259: Got command!
Received: []
Closed client socket
Port 9995: Received new client connection
Received: [guiserver enable_amplitude=true]
['enable_amplitude=true']
enable_amplitude=true
2
cmd_str:  guiserver enable_amplitude=true
cmd_dict:  {'guiserver': {'enable_amplitude': 'true'}}
Key: [guiserver]
{'enable_amplitude': 'true'}
Param_out[enable_amplitude]= True <class 'bool'>
Returned command: {'guiserver': {'enable_amplitude': True}}
1562625427.570596: Got command!
Received: []
Closed client socket
Port 9994: Received new client connection
Received: [guiserver enable_fourier=true]
['enable_fourier=true']
enable_fourier=true
2
cmd_str:  guiserver enable_fourier=true
cmd_dict:  {'guiserver': {'enable_fourier': 'true'}}
Key: [guiserver]
{'enable_fourier': 'true'}
Param_out[enable_fourier]= True <class 'bool'>
Returned command: {'guiserver': {'enable_fourier': True}}
1562625429.612556: Got command!
Received: []
Closed client socket
Port 9993: Received new client connection
Received: [framesource exec=run]
['exec=run']
exec=run
2
cmd_str:  framesource exec=run
cmd_dict:  {'framesource': {'exec': 'run'}}
Key: [framesource]
{'exec': 'run'}
Enumlist: ['IDLE', 'RUN']
Param_out[exec]= run <class 'str'>
Returned command: {'framesource': {'exec': 'run'}}
1562625432.271349: Got command!
Received: []
Closed client socket
Framesource got command
{'framesource': {'exec': 'run'}}
Mode = [camera]
Started client thread
1562625432.304934: Got Frame!
Reconstructor received image
1562625432.309166: Reconstructor:  Got Image!
Framesource: Received "Reconstruction_Metadata"
Guiserver: Received meta of type:  <class 'dhmsw.metadata_classes.Reconstruction_Metadata'>
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ryzen/Desktop/public_git/dhm_suite/dhmsw/dhmsw/reconstructor.py", line 356, in reconst_thread
    self.perform_reconstruction(data)
  File "/home/ryzen/Desktop/public_git/dhm_suite/dhmsw/dhmsw/reconstructor.py", line 489, in perform_reconstruction
    raise e
  File "/home/ryzen/Desktop/public_git/dhm_suite/dhmsw/dhmsw/reconstructor.py", line 406, in perform_reconstruction
    holo.ft_hologram
  File "/usr/local/lib/python3.6/dist-packages/shampoo-0.1.dev336-py3.6.egg/shampoo/reconstruction.py", line 459, in ft_hologram
    self._ft_hologram = fftshift(fft2(self.hologram))
  File "/usr/local/lib/python3.6/dist-packages/shampoo-0.1.dev336-py3.6.egg/shampoo/fftutils.py", line 71, in fft2
    self._fft3.input_array[:,:,0] = array
ValueError: could not broadcast input array from shape (1024,1024) into shape (2048,2048)

1562625432.454183: Got Frame!
Reconstructor received image
1562625432.620763: Got Frame!
Reconstructor received image
```

**Comment by sfregoso** [comment]
This issue occurs in the Shampoo code with width and height smaller than 2048.  Will look into this.

**Comment by sfregoso** [comment]
Frank needed to updated his version of Shampoo.  After he updated it the issue went away.
